### ISSUE TITLE
Laporan Partisipasi RCA > Partisipasi Pegawai : hasil print tidak sesuai dengan data di aplikasi.

### ISSUE THREAD

**Issue by shuLhan** [x10c/k3pl#1]
![RCA - partisipasi pegawai 01](https://f.cloud.github.com/assets/43306/193796/349fdb50-7f92-11e2-993d-c946528f7ef0.png)

![RCA - partisipasi pegawai 02](https://f.cloud.github.com/assets/43306/193797/373c42cc-7f92-11e2-9a92-48f0f5a71287.png)

**Comment by xkjRZx** [comment]
bug fix #1 with https://github.com/x10c/k3pl/commit/8ee4bfa6b6e4468346719a924e6fab5bdd13d25e
