### ISSUE TITLE
Laporan Partisipasi RCA > Partisipasi Organisasi: hasil print tidak sesuai dengan data di aplikasi.

### ISSUE THREAD

**Issue by shuLhan** [x10c/k3pl#2]
![RCA - partisipasi organisasi 01](https://f.cloud.github.com/assets/43306/193800/55b17f6a-7f92-11e2-812f-612c7805485e.png)

![RCA - partisipasi organisasi 02](https://f.cloud.github.com/assets/43306/193803/59b3a548-7f92-11e2-8cfb-ee25098390f8.png)

**Comment by xkjRZx** [comment]
bug fix #2 with https://github.com/x10c/k3pl/commit/8ee4bfa6b6e4468346719a924e6fab5bdd13d25e
