### ISSUE TITLE
Laporan Severity RCA : muncul error pada saat dicetak, dan hasilnya kosong.

### ISSUE THREAD

**Issue by shuLhan** [x10c/k3pl#6]
Error message:
![RCA - Laporan Severity - Print error 01](https://f.cloud.github.com/assets/43306/193824/febb20d4-7f92-11e2-813e-91745169dec3.png)

Hasil cetak:
![RCA - Laporan Severity - Print error 02](https://f.cloud.github.com/assets/43306/193828/0288254a-7f93-11e2-9c16-50ceb4f0a670.png)

**Comment by xkjRZx** [comment]
has been checked and is OK. 

evidence Laporan Severity Web & Xls
- Organisasi
  ![lap_severity_org_web](https://f.cloud.github.com/assets/3523965/246081/5f8ae7a8-8a94-11e2-9f20-870d05a25465.JPG)
  ![lap_severity_org_xls](https://f.cloud.github.com/assets/3523965/246083/66b1e068-8a94-11e2-9488-5a690a46b585.JPG)
- Wilayah
  ![lap_severity_wil_web](https://f.cloud.github.com/assets/3523965/246086/70339302-8a94-11e2-8a51-36561e0021be.JPG)
  ![lap_severity_wil_xls](https://f.cloud.github.com/assets/3523965/246087/768121de-8a94-11e2-8328-8f81b50f7e75.JPG)
